apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: python-eklzdwsb 
  janus-idp.io/tekton: python-eklzdwsb
  backstage.io/kubernetes-id: python-eklzdwsb
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: python-eklzdwsb
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml